Sync with lilo 1:23.2-1
New manuals: lilo-uuid-diskid(8) update-lilo(8)
Deleted manuals: activate(8) lilo_find_mbr(8)
Handled in POD: liloconfig(8), lilo-uuid-diskid(8) update-lilo(8)

  lilo: 396t, 46f, 45u

git-svn-id: svn+ssh://svn.debian.org/svn/pkg-manpages-fr/manpages-fr-extra/trunk@2290 d962e65b-5e0b-0410-9890-ddd2169a14ac

diff --git a/Makefile.common b/Makefile.common
--- a/Makefile.common
+++ b/Makefile.common
@@ -53,6 +53,33 @@ define check_link
   fi
 endef
 
+define create_from_pod
+  set -e; \
+  echo -n "Creating manual pages from POD..."; \
+  for file in fr/pod/*.pod; do \
+    if [ -e $$file ]; then \
+      sh C/pod/pod2manpage $$file; \
+    fi; \
+  done; \
+  echo -n "Move manual pages from POD to their actual location..."; \
+  for file in fr/pod/*; do \
+    if [ -e $$file ]; then \
+      section=`echo $$file | sed -e "s/^.*\.\([1-9]\|pod\)\([^1-9.][^.]*\)*$$/\1/"`; \
+      if [ `expr $$section : "pod"` = 0 ]; then \
+        if [ `expr $$section : "[1-9]"` = 0 ]; then \
+          echo "failed."; \
+          exit 0; \
+        fi; \
+        if [ ! -d fr/man$$section ]; then \
+          mkdir fr/man$$section; \
+        fi; \
+        cp $$file fr/man$$section; \
+        echo "done."; \
+      fi; \
+    fi; \
+  done
+endef
+
 all: build
 
 pre-build:
@@ -61,6 +88,9 @@ po4a-build:
 	po4a --previous $(PO4ACONFIGFILE)
 
 post-build:
+	@if [ -d fr/pod ]; then \
+	  $(call create_from_pod); \
+	fi;
 	@if [ -e links ]; then \
 	  cat links | while read line; do \
 	    LINK=`echo $$line | cut -d " " -f 1`; \
