Added (limited) infrastructure to check links.
git-svn-id: svn+ssh://svn.debian.org/svn/pkg-manpages-fr/manpages-fr-extra/trunk@1920 d962e65b-5e0b-0410-9890-ddd2169a14ac

diff --git a/Makefile.common b/Makefile.common
--- a/Makefile.common
+++ b/Makefile.common
@@ -36,6 +36,23 @@ define create_link
   fi
 endef
 
+define check_link
+  set -e; \
+  echo -n "Checking if $(2) is still a link to $(1)... "; \
+  section1=`echo $(1) | sed -e "s/^.*\.\([1-9]\)\([^1-9.][^.]*\)*$$/\1/"`; \
+  section2=`echo $(2) | sed -e "s/^.*\.\([1-9]\)\([^1-9.][^.]*\)*$$/\1/"`; \
+  if [ `expr $$section1 : "[1-9]"` == 0 -o `expr $$section2 : "[1-9]"` == 0 ]; then \
+    echo "failed."; \
+    exit 0; \
+  fi; \
+  if cmp C/man$$section1/$(1) C/man$$section2/$(2); then \
+      echo "done."; \
+  else \
+      echo "failed."; \
+      exit 1; \
+  fi
+endef
+
 all: build
 
 pre-build:
